// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1eMapPZyPz5J9bSVX3Sa7byUjYkIpsAk',
    appId: '1:249167987682:web:5690b69c63b3f5e3836fbb',
    messagingSenderId: '249167987682',
    projectId: 'trackflow-cloud-engine',
    authDomain: 'trackflow-cloud-engine.firebaseapp.com',
    storageBucket: 'trackflow-cloud-engine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIuXGZ-cK5HokA6dlLjbn-y2T_fxtkZ10',
    appId: '1:249167987682:android:ddb6d8a1121c8526836fbb',
    messagingSenderId: '249167987682',
    projectId: 'trackflow-cloud-engine',
    storageBucket: 'trackflow-cloud-engine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh5-Nzaw5f1PjqBBorZXPQ7GxRFWLWU8Y',
    appId: '1:249167987682:ios:d4c6943e917dd5bb836fbb',
    messagingSenderId: '249167987682',
    projectId: 'trackflow-cloud-engine',
    storageBucket: 'trackflow-cloud-engine.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh5-Nzaw5f1PjqBBorZXPQ7GxRFWLWU8Y',
    appId: '1:249167987682:ios:d4c6943e917dd5bb836fbb',
    messagingSenderId: '249167987682',
    projectId: 'trackflow-cloud-engine',
    storageBucket: 'trackflow-cloud-engine.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1eMapPZyPz5J9bSVX3Sa7byUjYkIpsAk',
    appId: '1:249167987682:web:88943813508a3731836fbb',
    messagingSenderId: '249167987682',
    projectId: 'trackflow-cloud-engine',
    authDomain: 'trackflow-cloud-engine.firebaseapp.com',
    storageBucket: 'trackflow-cloud-engine.firebasestorage.app',
  );
}
